//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Id { get; set; }
        public int Номер_дела { get; set; }
        public int Id_судьи { get; set; }
        public int Id_пострадавшего { get; set; }
        public int Id_обвиняемого { get; set; }
        public int Номер_статьи { get; set; }
        public System.DateTime Дата_открытия_дела { get; set; }
        public System.DateTime Дата_закрытия_дела { get; set; }
    
        public virtual Accused Accused { get; set; }
        public virtual Victim Victim { get; set; }
        public virtual Judge Judge { get; set; }
    }
}
