//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliceEntities : DbContext
    {
        public PoliceEntities()
            : base("name=PoliceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accused> Accuseds { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<EmployeVictim> EmployeVictims { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Judge> Judges { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Subsection> Subsections { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Victim> Victims { get; set; }
    }
}
